site_name: SCBC Pecan
site_url: 'https://ding0t.github.io/scbc_pecan/'

repo_url: 'https://github.com/ding0t/scbc_pecan'

# main navigation
nav:
  - Home: README.md
  - Tool cheatsheets: 
    - Tools list: './lessons/tools.md'
    - Linux terminal: './lessons/linux_shell.md'
    - Ghidra: './lessons/ghidra.md'
    - Generative AI: './lessons/ai_coding.md'
  - General: 
    - Welcome: './lessons/01_intro.md'
    - Character encoding: './lessons/02_encoding.md'
    - Base64: './lessons/03_base64.md'
    - Python: './lessons/04_python.md'
  - Web:
    - Web client side: './lessons/05_web_robots_cookies.md'
    - Web server side : './lessons/06_web_server.md'
  - Labs:
    - General (picoCTF):
      - Skills 1: './labs/pico_playlist_general_1.md'
      - Skills 2: './labs/pico_playlist_general_2.md'
      - playlist (picoCTF): './labs/pico_playlist_python.md'
    - Web:
      - picoCTF web - client side: './labs/pico_web_client.md'
      - picoCTF web - client side: './labs/pico_web_server.md'
      - pecan web: './labs/pecan_web.md'
    - Crypto:
      - Love letter (PECAN): './labs/pecan_crypto_love_letter.md'


# material theme has good documentation and configuration
theme:
  name: material
  palette:
    scheme: default
    primary: blue
  features:
    - search.suggest
    - search.highlight
    - toc.follow
    - navigation.tracking
    - navigation.path
    - navigation.sections
    - navigation.expand

# pip install mkdocstrings[python]
# https://realpython.com/python-project-documentation-with-mkdocs/
plugins:
  - tags
  - search
  - mkdocstrings

markdown_extensions:
  - tables
  # enable code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  # emojis - search here https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg