site_name: SCBC Pecan
site_url: 'https://ding0t.github.io/scbc_pecan/'

repo_url: 'https://github.com/ding0t/scbc_pecan'

# main navigation
nav:
  - Home: README.md
  - Tools: 
    - Tools list: './lessons/tools.md'
    - Linux terminal: './lessons/linux_shell.md'
    - Ghidra: './lessons/ghidra.md'
    - Generative AI: './lessons/ai_coding.md'
  - Lessons: 
    - 01 - Welcome: './lessons/lesson_01.md'
    - 02 - Character encoding: './lessons/lesson_02.md'
    - 03 - Base64: './lessons/lesson_03.md'
    - 04 - Python: './lessons/lesson_04.md'
    - 05 - Web Exploitation: './lessons/lesson_05.md'
  - Labs:
    - General (picoCTF):
      - Skills 1: './labs/pico_playlist_general_1.md'
      - Skills 2: './labs/pico_playlist_general_2.md'
    - Python : 
      - playlist (picoCTF): './labs/pico_playlist_python.md'
    - Crypto:
      - Love letter (PECAN): './labs/pecan_crypto_love_letter.md'
    - Web Exploitation:
      - picoCTF web lab: './labs/pico_web_exploitation.md'

# material theme has good documentation and configuration
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
  features:
    - search.suggest
    - search.highlight
    - toc.follow
    - navigation.tracking
    - navigation.path
    - navigation.sections
    - navigation.expand

plugins:
  - tags
  - search

markdown_extensions:
  - tables
  # enable code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  # emojis - search here https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg