name: Marp CI Workflow

env:
  JOB_SRC_DIR: 'docs/slides'
  JOB_BLD_DIR: 'docs/slides'

on:
  push:
    paths:
      - 'docs/slides/**'
    branches:
      - master 
      - main
  # Allow manual build
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Jobs are complete new runner instances
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      #- name: Ensure build dir exists
      #  run: mkdir -p ${{env.JOB_BLD_DIR}}
#
      #- name: Copy images to build
      #  run: cp -R ${{env.JOB_SRC_DIR}}/img ${{env.JOB_BLD_DIR}}/img

      - name: Marp Build (README)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: -I ${{env.JOB_SRC_DIR}}/ -o ${{env.JOB_BLD_DIR}}/ --html
        env:
          MARP_USER: root:root

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: marp-slides
          path: ${{env.JOB_BLD_DIR}}/**

      - name: Configure git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage build files
        run: git add ${{env.JOB_BLD_DIR}}/**
     
      - name: Commit changed files
        run: git commit -m "CI updating presentation files." 
    
      - name: Push build
        run: git push origin main

  # References
  # - https://github.com/robalexdev/marp-to-pages/blob/main/.github/workflows/marp-to-pages.yml
  # - https://www.hashbangcode.com/snippets/marp-github-action-build-presentation-files
  # - https://dev.to/chris_ayers/marp-create-presentations-with-markdown-5e6k?comments_sort=oldest